### ISSUE TITLE
Start by Wireless debugging on Android 11?

### ISSUE THREAD

**Issue by publicclassoverflow** [KieronQuinn/DarQ#17]
A few other apps (e.g. [Shizuku](https://github.com/RikkaApps/Shizuku) that are also started using adb commands are exploring solutions to start themselves by utilizing the new wireless debugging feature in Android 11. Any plans for something like that? It will be a great feature to have such that we can finally ditch the cable + terminal! Thanks!

**Comment by KieronQuinn** [comment]
This already worked as it turned out. The script doesn't ask you to pair or connect, because it would really be no more helpful than simply doing it yourself. If you run `adb pair` and `adb connect` (on a Mac/Linux) or `tools\adb pair` and `tools\adb connect` (on Windows with the tools\adb binary up to date - which it now is in 1.1) it will connect and the script will then run fine with no changes.

**Comment by publicclassoverflow** [comment]
As I mentioned that in Shizuku, once the device has been paired/connected via adb, it won't require re-pair or re-connect with the pc after reboot. I just launch shizuku and do "start via wireless debugging". I didn't mean to skip just the physical cable connection step (this is in fact easier and faster to do than connecting the device to pc via wireless debugging), but the actual "rundarq-windows.bat" script.
