### ISSUE TITLE
No Updates for 6 months

### ISSUE THREAD

**Issue by foxnoodles** [KieronQuinn/DarQ#18]
Any plans?

**Comment by KieronQuinn** [comment]
For future reference, making an issue for this isn't nice. DarQ was in a stable position and didn't really need a big update. Today's update was mostly bug fix for the very minor issues it had that didn't affect usability, and purely because I had a bit of time to spare on it.

If you'd like to add stuff, feel free to make a pull request. But don't do this.

**Comment by foxnoodles** [comment]
Wow that is some next level beta male reaction right there. Lol do create issues on my github reeeee. Geez.
