### ISSUE TITLE
[FEATURE] - Toggle to use a Denylist instead of Allowlist

### ISSUE THREAD

**Issue by bgiesing** [KieronQuinn/DarQ#36]
Currently how the app works is you either select specific apps to allow OR you allow all apps, you currently can't allow all BUT select a few specific apps to keep Light. It would be great if the "Always use Force Dark" option instead acted as a toggle to change the allowlist to a denylist so you can have everything Dark by default but selectively turn off apps (like ones that might have issues)

**Comment by KieronQuinn** [comment]
As I've stated many times in the XDA thread, this won't happen. Force dark is intended to be a developer option, and it regularly breaks apps. With a whitelist, you must consciously choose to pick which apps are themed, and will know to turn them off. With a blacklist, this is not the case.

The enable/disable code is also not immediate when an app launches, so a blacklist would lead to instances of apps being incorrectly force dark when they shouldn't be, rather than the much safer case where they're not themed with the whitelist.
