### ISSUE TITLE
Hide from unaffected apps?

### ISSUE THREAD

**Issue by IngwiePhoenix** [KieronQuinn/DarQ#59]
Hello!

I only want DarQ to affect exactly two applications. However, "Applist Detector", which is not set as an app to have Dark Mode forced on, still sees it:

![Screenshot_20220411-001726_Applist_Detector](https://user-images.githubusercontent.com/2893716/162642215-c82f6099-1185-4f61-ad5c-e7d894f1f1b8.png)

Is there any way I can hide it? I need it for some apps due to my visual impairment and those apps not supporting a native dark mode.

Thanks and kind regards,
Ingwie

**Comment by KieronQuinn** [comment]
I think this is probably because it's using the `QUERY_ALL_PACKAGES` permission, which it requires to show the app list for you to pick which apps to enable DarQ on. There's nothing I can do about that, as it's an absolute requirement. As a shell/root app, it would be able to access this information (albeit much more slowly - hence why it uses the permission) via IPC, so it having the permission is redundant security-wise.
